// The following directive is necessary to make the package coherent:
// +build ignore

package main

import (
	"io/ioutil"
	"log"
	"os"
	"text/template"
	"time"
)

const FILENAME = "../../../data/people.json"

// This program generates people.go. It can be invoked by running
// go generate
func main() {
	content, err := ioutil.ReadFile(FILENAME)
	die(err)

	f, err := os.Create("generated-people.go")
	die(err)

	packageTemplate.Execute(f, struct {
		Timestamp time.Time
		File      string
		JSON      string
	}{
		Timestamp: time.Now(),
		File:      FILENAME,
		JSON:      string(content),
	})
}

func die(err error) {
	if err != nil {
		log.Fatal(err)
	}
}

var packageTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}
// using data from file: {{ .File }}
package people

const People = ` +
	"`" +
	`{{ .JSON }}` +
	"`" +
	`
`))
